language: cpp
os: linux
compiler: gcc
sudo: required
dist: xenial
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake libboost-all-dev
script: 
    - mkdir build && cd build
    - cmake  .. && make build-tests
    - make test